server:
  port: 8081
  contextPath: 
  tomcat:
    additional-tld-skip-patterns : "javacpp.jar, *javacv*.jar, ffmpeg-*.jar"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wedding
    username: wedding_app
    password: wedding_app
    driverClassName: org.postgresql.Driver
profile:
  root:
    directory: wedding
info:
  root:
    directory: wedding/information
gallery:
  root:
    directory: dev
  distribution:
    server: http://data.debugroom.org.s3.amazonaws.com
  bucket:
    name: debugroom-wedding-gallery
  create:
    thumbnail:
      sqs:
        notification:
          queue:
            name: CreateThumbnailNotify_Dev