spring:
  profiles:
    active: dev,jpa
  http:
    multipart:
      enabled: true
      max-file-size: 10000000000
      max-request-size: 10000000000
profile:
  root:
    directory: wedding/profile
  directory: image
  image:
    file:
      name: image
info:
  root:
    directory: wedding/info
gallery:
  root:
    directory: wedding/gallery
  image:
    original:
      directory: image/original
      file:
        name: image
    thumbnail:
      directory: image/thumbnail
      file:
        name: image-thumbnail
      width:  100
      height: 75
  movie:
    original:
      directory: movie/original
      file:
        name: movie
    thumbnail:
      directory: movie/thumbnail
      file:
        name: movie-thumbnail
      width:  100
      height: 75
      frame:
        start: 100
  aws:
    upload:
      role:
        name: wedding-gallery-upload-role
        session:
          name: wedding-gallery-upload-session
      durationseconds: 864000
      limitBytes: 10000000000
      acl: private
    download:
      role:
        name: wedding-gallery-download-role
        session:
          name: wedding-gallery-download-session
      durationseconds: 600
bucket:
  name: data.debugroom.org
queue:
  endpoint: https://sqs.ap-northeast-1.amazonaws.com/
protocol: http
cloud:
  aws:
    stack:
      auto: false
    credentials:
      instanceProfile: false
      profileName: 
    region:
      auto: false