spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://${dbserver.port.5432.tcp.addr}:${dbserver.port.5432.tcp.port}/wedding
    username: ${dbserver.app.username}
    password: ${dbserver.app.password}
    driverClassName: org.postgresql.Driver
logging:
  file: logs/app.log
  level:
    org.springframework.web: INFO
protocol: https
server:
    port: 8080
    contextPath: /wedding
profile:
  root:
    directory: wedding
info:
  root:
    directory: wedding/information
gallery:
  root:
    directory: production
  distribution:
    server: http://data.debugroom.org.s3.amazonaws.com
  create:
    thumbnail:
      sqs:
        notification:
          queue:
            name: CreateThumbnailNotify
cloud:
  aws:
    credentials:
      accessKey: ${aws.access.key.id}
      secretKey: ${aws.secret.access.key}
    region:
      static: ${aws.default.resion}