server:
  port: 8087
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wedding
    username: wedding_app
    password: wedding_app
    driverClassName: org.postgresql.Driver
gallery:
  root:
    directory: /Users/kawabatakouhei/Documents/work/apps/gallery