
/* Drop Tables */

DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS AFFILIATION;
DROP TABLE IF EXISTS CREDENTIAL;
DROP TABLE IF EXISTS EMAIL;
DROP TABLE IF EXISTS FNCTION;
DROP TABLE IF EXISTS GROUP_FOLDER;
DROP TABLE IF EXISTS MOVIE_RELATED_FOLDER;
DROP TABLE IF EXISTS PHOTO_RELATED_FOLDER;
DROP TABLE IF EXISTS USER_RELATED_FOLDER;
DROP TABLE IF EXISTS FOLDER;
DROP TABLE IF EXISTS GROUP_NOTIFICATION;
DROP TABLE IF EXISTS GROUP_VISIBLE_MOVIE;
DROP TABLE IF EXISTS GROUP_VISIBLE_PHOTO;
DROP TABLE IF EXISTS GRP;
DROP TABLE IF EXISTS NOTIFICATION;
DROP TABLE IF EXISTS INFORMATION;
DROP TABLE IF EXISTS MENU;
DROP TABLE IF EXISTS MESSAGE;
DROP TABLE IF EXISTS MESSAGE_BOARD;
DROP TABLE IF EXISTS MOVIE_RELATED_USER;
DROP TABLE IF EXISTS MOVIE;
DROP TABLE IF EXISTS PHOTO_RELATED_USER;
DROP TABLE IF EXISTS PHOTO;
DROP TABLE IF EXISTS REQUEST_STATUS;
DROP TABLE IF EXISTS REQUEST;
DROP TABLE IF EXISTS USR;




/* Create Tables */

-- 住所
CREATE TABLE ADDRESS
(
	-- ユーザID
	USER_ID varchar(8) NOT NULL,
	-- 郵便番号
	POST_CD char(8),
	-- 住所
	ADDRESS varchar(255),
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (USER_ID)
) WITHOUT OIDS;


-- 所属
CREATE TABLE AFFILIATION
(
	-- グループID
	GROUP_ID char(10) NOT NULL,
	-- ユーザID
	USER_ID varchar(8) NOT NULL,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (GROUP_ID, USER_ID),
	UNIQUE (GROUP_ID, USER_ID)
) WITHOUT OIDS;


-- 認証
CREATE TABLE CREDENTIAL
(
	-- ユーザID
	USER_ID varchar(8) NOT NULL,
	-- 認証タイプ
	CREDENTIAL_TYPE varchar NOT NULL,
	-- 認証キー
	CREDENTIAL_KEY varchar,
	-- 有効日時
	VALID_DATE timestamp,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (USER_ID, CREDENTIAL_TYPE),
	UNIQUE (USER_ID, CREDENTIAL_TYPE)
) WITHOUT OIDS;


-- メール
CREATE TABLE EMAIL
(
	-- ユーザID
	USER_ID varchar(8) NOT NULL,
	-- メールID
	EMAIL_ID int NOT NULL,
	-- メールアドレス
	EMAIL varchar(100),
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (USER_ID, EMAIL_ID),
	UNIQUE (USER_ID, EMAIL_ID)
) WITHOUT OIDS;


-- 機能
CREATE TABLE FNCTION
(
	-- メニューID
	MENU_ID varchar(4) NOT NULL,
	-- 機能ID
	FUNCTION_ID char(4) NOT NULL,
	-- 機能名
	FUNCTION_NAME varchar(100),
	-- URL
	URL varchar,
	-- パス変数を持つ
	HAS_PATHVARIABLES boolean,
	-- 使用可能開始日時
	USABLE_START_DATE date,
	-- 使用可能終了日時
	USABLE_END_DATE date,
	-- 権限レベル
	AUTHORITY_LEVEL int,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (MENU_ID, FUNCTION_ID),
	UNIQUE (MENU_ID, FUNCTION_ID)
) WITHOUT OIDS;


-- フォルダ
CREATE TABLE FOLDER
(
	-- フォルダID
	FOLDER_ID char(12) NOT NULL,
	-- フォルダ名
	FOLDER_NAME varchar,
	-- 親フォルダID
	PARENT_FOLDER_ID char(12),
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	-- ユーザID
	USER_ID varchar(8) NOT NULL,
	PRIMARY KEY (FOLDER_ID)
) WITHOUT OIDS;


-- グループフォルダ
CREATE TABLE GROUP_FOLDER
(
	-- フォルダID
	FOLDER_ID char(12) NOT NULL,
	-- グループID
	GROUP_ID char(10) NOT NULL,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (FOLDER_ID, GROUP_ID),
	UNIQUE (FOLDER_ID, GROUP_ID)
) WITHOUT OIDS;


-- グループ通知
CREATE TABLE GROUP_NOTIFICATION
(
	-- グループID
	GROUP_ID char(10) NOT NULL,
	-- インフォID
	INFO_ID char(8) NOT NULL,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (GROUP_ID, INFO_ID),
	UNIQUE (GROUP_ID, INFO_ID)
) WITHOUT OIDS;


-- グループ閲覧可能ムービー
CREATE TABLE GROUP_VISIBLE_MOVIE
(
	-- ムービーID
	MOVIE_ID char(10) NOT NULL,
	-- グループID
	GROUP_ID char(10) NOT NULL,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (MOVIE_ID, GROUP_ID),
	UNIQUE (MOVIE_ID, GROUP_ID)
) WITHOUT OIDS;


-- グループ閲覧可能写真
CREATE TABLE GROUP_VISIBLE_PHOTO
(
	-- グループID
	GROUP_ID char(10) NOT NULL,
	-- 写真ID
	PHOTO_ID char(10) NOT NULL,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (GROUP_ID, PHOTO_ID),
	UNIQUE (GROUP_ID, PHOTO_ID)
) WITHOUT OIDS;


-- グループ
CREATE TABLE GRP
(
	-- グループID
	GROUP_ID char(10) NOT NULL,
	-- グループ名
	GROUP_NAME varchar(256),
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (GROUP_ID)
) WITHOUT OIDS;


-- インフォメーション
CREATE TABLE INFORMATION
(
	-- インフォID
	INFO_ID char(8) NOT NULL,
	-- タイトル
	TITLE varchar(256),
	-- インフォページパス
	INFO_PAGE_PATH varchar,
	-- 登録日時
	REGISTRATED_DATE timestamp,
	-- 公開日時
	RELEASE_DATE timestamp,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (INFO_ID)
) WITHOUT OIDS;


-- メニュー
CREATE TABLE MENU
(
	-- メニューID
	MENU_ID varchar(4) NOT NULL,
	-- メニュー名
	MENU_NAME varchar,
	-- URL
	URL varchar,
	-- パス変数を持つ
	HAS_PATHVARIABLES boolean,
	-- 使用可能開始日時
	USABLE_START_DATE timestamp,
	-- 使用可能終了日時
	USABLE_END_DATE timestamp,
	-- 権限レベル
	AUTHORITY_LEVEL int,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (MENU_ID)
) WITHOUT OIDS;


-- メッセージ
CREATE TABLE MESSAGE
(
	-- 掲示板ID
	MESSAGE_BOARD_ID char(8) NOT NULL,
	-- メッセージNo
	MESSAGE_NO int NOT NULL,
	-- メッセージ
	MESSAGE varchar,
	-- いいねカウント
	LIKE_COUNT int,
	-- 関連写真ID
	RELATED_PHOTO_ID char(10),
	-- 関連ムービーID
	RELATED_MOVIE_ID char(10),
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (MESSAGE_BOARD_ID, MESSAGE_NO),
	UNIQUE (MESSAGE_BOARD_ID, MESSAGE_NO)
) WITHOUT OIDS;


-- 掲示板
CREATE TABLE MESSAGE_BOARD
(
	-- 掲示板ID
	MESSAGE_BOARD_ID char(8) NOT NULL,
	-- タイトル
	TITLE varchar(512),
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (MESSAGE_BOARD_ID)
) WITHOUT OIDS;


-- ムービー
CREATE TABLE MOVIE
(
	-- ムービーID
	MOVIE_ID char(10) NOT NULL,
	-- ファイルパス
	FILE_PATH varchar,
	-- サムネイルファイルパス
	THUMBNAIL_FILE_PATH varchar,
	-- 制御有無
	IS_CONTROLED boolean,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (MOVIE_ID)
) WITHOUT OIDS;


-- フォルダ関連ムービー
CREATE TABLE MOVIE_RELATED_FOLDER
(
	-- ムービーID
	MOVIE_ID char(10) NOT NULL,
	-- フォルダID
	FOLDER_ID char(12) NOT NULL,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (MOVIE_ID, FOLDER_ID)
) WITHOUT OIDS;


-- ユーザ関連ムービー
CREATE TABLE MOVIE_RELATED_USER
(
	-- ムービーID
	MOVIE_ID char(10) NOT NULL,
	-- ユーザID
	USER_ID varchar(8) NOT NULL,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (MOVIE_ID, USER_ID),
	UNIQUE (MOVIE_ID, USER_ID)
) WITHOUT OIDS;


-- 通知
CREATE TABLE NOTIFICATION
(
	-- インフォID
	INFO_ID char(8) NOT NULL,
	-- ユーザID
	USER_ID varchar(8) NOT NULL,
	-- アクセス済み
	IS_ACCESSED boolean,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (INFO_ID, USER_ID),
	UNIQUE (USER_ID, INFO_ID)
) WITHOUT OIDS;


-- 写真
CREATE TABLE PHOTO
(
	-- 写真ID
	PHOTO_ID char(10) NOT NULL,
	-- ファイルパス
	FILE_PATH varchar,
	-- サムネイルファイルパス
	THUMBNAIL_FILE_PATH varchar,
	-- 制御有無
	IS_CONTROLED boolean,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (PHOTO_ID)
) WITHOUT OIDS;


-- フォルダ関連フォト
CREATE TABLE PHOTO_RELATED_FOLDER
(
	-- 写真ID
	PHOTO_ID char(10) NOT NULL,
	-- フォルダID
	FOLDER_ID char(12) NOT NULL,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (PHOTO_ID, FOLDER_ID),
	UNIQUE (PHOTO_ID, FOLDER_ID)
) WITHOUT OIDS;


-- ユーザ関連フォト
CREATE TABLE PHOTO_RELATED_USER
(
	-- 写真ID
	PHOTO_ID char(10) NOT NULL,
	-- ユーザID
	USER_ID varchar(8) NOT NULL,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (PHOTO_ID, USER_ID),
	UNIQUE (PHOTO_ID, USER_ID)
) WITHOUT OIDS;


-- 依頼
CREATE TABLE REQUEST
(
	-- 依頼ID
	REQUEST_ID char(4) NOT NULL,
	-- タイトル
	TITLE varchar(512),
	-- 依頼内容
	REQUEST_CONTENTS varchar,
	-- 登録日時
	REGISTRATED_DATE timestamp,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (REQUEST_ID)
) WITHOUT OIDS;


-- 依頼状況
CREATE TABLE REQUEST_STATUS
(
	-- 依頼ID
	REQUEST_ID char(4) NOT NULL,
	-- ユーザID
	USER_ID varchar(8) NOT NULL,
	-- 回答済み
	IS_ANSWERED boolean,
	-- 承認
	IS_APPROVED boolean,
	-- 回答内容
	RESPONSE varchar,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (REQUEST_ID, USER_ID),
	UNIQUE (REQUEST_ID, USER_ID)
) WITHOUT OIDS;


-- ユーザ関連フォルダ
CREATE TABLE USER_RELATED_FOLDER
(
	-- フォルダID
	FOLDER_ID char(12) NOT NULL,
	-- ユーザID
	USER_ID varchar(8) NOT NULL,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (FOLDER_ID, USER_ID),
	UNIQUE (FOLDER_ID, USER_ID)
) WITHOUT OIDS;


-- ユーザ
CREATE TABLE USR
(
	-- ユーザID
	USER_ID varchar(8) NOT NULL,
	-- 苗字
	LAST_NAME varchar,
	-- 名前
	FIRST_NAME varchar,
	-- ログインID
	LOGIN_ID varchar UNIQUE,
	-- 画像ファイルパス
	IMAGE_FILE_PATH varchar,
	-- 権限レベル
	AUTHORITY_LEVEL int,
	-- 花嫁側
	IS_BRIDE_SIDE boolean,
	-- 最終ログイン日時
	LAST_LOGIN_DATE timestamp,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_DATE timestamp,
	PRIMARY KEY (USER_ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE GROUP_FOLDER
	ADD FOREIGN KEY (FOLDER_ID)
	REFERENCES FOLDER (FOLDER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MOVIE_RELATED_FOLDER
	ADD FOREIGN KEY (FOLDER_ID)
	REFERENCES FOLDER (FOLDER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PHOTO_RELATED_FOLDER
	ADD FOREIGN KEY (FOLDER_ID)
	REFERENCES FOLDER (FOLDER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_RELATED_FOLDER
	ADD FOREIGN KEY (FOLDER_ID)
	REFERENCES FOLDER (FOLDER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AFFILIATION
	ADD FOREIGN KEY (GROUP_ID)
	REFERENCES GRP (GROUP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GROUP_FOLDER
	ADD FOREIGN KEY (GROUP_ID)
	REFERENCES GRP (GROUP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GROUP_NOTIFICATION
	ADD FOREIGN KEY (GROUP_ID)
	REFERENCES GRP (GROUP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GROUP_VISIBLE_MOVIE
	ADD FOREIGN KEY (GROUP_ID)
	REFERENCES GRP (GROUP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GROUP_VISIBLE_PHOTO
	ADD FOREIGN KEY (GROUP_ID)
	REFERENCES GRP (GROUP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GROUP_NOTIFICATION
	ADD FOREIGN KEY (INFO_ID)
	REFERENCES INFORMATION (INFO_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE NOTIFICATION
	ADD FOREIGN KEY (INFO_ID)
	REFERENCES INFORMATION (INFO_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FNCTION
	ADD FOREIGN KEY (MENU_ID)
	REFERENCES MENU (MENU_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MESSAGE
	ADD FOREIGN KEY (MESSAGE_BOARD_ID)
	REFERENCES MESSAGE_BOARD (MESSAGE_BOARD_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GROUP_VISIBLE_MOVIE
	ADD FOREIGN KEY (MOVIE_ID)
	REFERENCES MOVIE (MOVIE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MESSAGE
	ADD FOREIGN KEY (RELATED_MOVIE_ID)
	REFERENCES MOVIE (MOVIE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MOVIE_RELATED_FOLDER
	ADD FOREIGN KEY (MOVIE_ID)
	REFERENCES MOVIE (MOVIE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MOVIE_RELATED_USER
	ADD FOREIGN KEY (MOVIE_ID)
	REFERENCES MOVIE (MOVIE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GROUP_VISIBLE_PHOTO
	ADD FOREIGN KEY (PHOTO_ID)
	REFERENCES PHOTO (PHOTO_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MESSAGE
	ADD FOREIGN KEY (RELATED_PHOTO_ID)
	REFERENCES PHOTO (PHOTO_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PHOTO_RELATED_FOLDER
	ADD FOREIGN KEY (PHOTO_ID)
	REFERENCES PHOTO (PHOTO_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PHOTO_RELATED_USER
	ADD FOREIGN KEY (PHOTO_ID)
	REFERENCES PHOTO (PHOTO_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE REQUEST_STATUS
	ADD FOREIGN KEY (REQUEST_ID)
	REFERENCES REQUEST (REQUEST_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ADDRESS
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USR (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AFFILIATION
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USR (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CREDENTIAL
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USR (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE EMAIL
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USR (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FOLDER
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USR (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MOVIE_RELATED_USER
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USR (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE NOTIFICATION
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USR (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PHOTO_RELATED_USER
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USR (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE REQUEST_STATUS
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USR (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_RELATED_FOLDER
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USR (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Comments */

COMMENT ON TABLE ADDRESS IS '住所';
COMMENT ON COLUMN ADDRESS.USER_ID IS 'ユーザID';
COMMENT ON COLUMN ADDRESS.POST_CD IS '郵便番号';
COMMENT ON COLUMN ADDRESS.ADDRESS IS '住所';
COMMENT ON COLUMN ADDRESS.VER IS 'バージョン';
COMMENT ON COLUMN ADDRESS.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE AFFILIATION IS '所属';
COMMENT ON COLUMN AFFILIATION.GROUP_ID IS 'グループID';
COMMENT ON COLUMN AFFILIATION.USER_ID IS 'ユーザID';
COMMENT ON COLUMN AFFILIATION.VER IS 'バージョン';
COMMENT ON COLUMN AFFILIATION.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE CREDENTIAL IS '認証';
COMMENT ON COLUMN CREDENTIAL.USER_ID IS 'ユーザID';
COMMENT ON COLUMN CREDENTIAL.CREDENTIAL_TYPE IS '認証タイプ';
COMMENT ON COLUMN CREDENTIAL.CREDENTIAL_KEY IS '認証キー';
COMMENT ON COLUMN CREDENTIAL.VALID_DATE IS '有効日時';
COMMENT ON COLUMN CREDENTIAL.VER IS 'バージョン';
COMMENT ON COLUMN CREDENTIAL.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE EMAIL IS 'メール';
COMMENT ON COLUMN EMAIL.USER_ID IS 'ユーザID';
COMMENT ON COLUMN EMAIL.EMAIL_ID IS 'メールID';
COMMENT ON COLUMN EMAIL.EMAIL IS 'メールアドレス';
COMMENT ON COLUMN EMAIL.VER IS 'バージョン';
COMMENT ON COLUMN EMAIL.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE FNCTION IS '機能';
COMMENT ON COLUMN FNCTION.MENU_ID IS 'メニューID';
COMMENT ON COLUMN FNCTION.FUNCTION_ID IS '機能ID';
COMMENT ON COLUMN FNCTION.FUNCTION_NAME IS '機能名';
COMMENT ON COLUMN FNCTION.URL IS 'URL';
COMMENT ON COLUMN FNCTION.HAS_PATHVARIABLES IS 'パス変数を持つ';
COMMENT ON COLUMN FNCTION.USABLE_START_DATE IS '使用可能開始日時';
COMMENT ON COLUMN FNCTION.USABLE_END_DATE IS '使用可能終了日時';
COMMENT ON COLUMN FNCTION.AUTHORITY_LEVEL IS '権限レベル';
COMMENT ON COLUMN FNCTION.VER IS 'バージョン';
COMMENT ON COLUMN FNCTION.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE FOLDER IS 'フォルダ';
COMMENT ON COLUMN FOLDER.FOLDER_ID IS 'フォルダID';
COMMENT ON COLUMN FOLDER.FOLDER_NAME IS 'フォルダ名';
COMMENT ON COLUMN FOLDER.PARENT_FOLDER_ID IS '親フォルダID';
COMMENT ON COLUMN FOLDER.VER IS 'バージョン';
COMMENT ON COLUMN FOLDER.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON COLUMN FOLDER.USER_ID IS 'ユーザID';
COMMENT ON TABLE GROUP_FOLDER IS 'グループフォルダ';
COMMENT ON COLUMN GROUP_FOLDER.FOLDER_ID IS 'フォルダID';
COMMENT ON COLUMN GROUP_FOLDER.GROUP_ID IS 'グループID';
COMMENT ON COLUMN GROUP_FOLDER.VER IS 'バージョン';
COMMENT ON COLUMN GROUP_FOLDER.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE GROUP_NOTIFICATION IS 'グループ通知';
COMMENT ON COLUMN GROUP_NOTIFICATION.GROUP_ID IS 'グループID';
COMMENT ON COLUMN GROUP_NOTIFICATION.INFO_ID IS 'インフォID';
COMMENT ON COLUMN GROUP_NOTIFICATION.VER IS 'バージョン';
COMMENT ON COLUMN GROUP_NOTIFICATION.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE GROUP_VISIBLE_MOVIE IS 'グループ閲覧可能ムービー';
COMMENT ON COLUMN GROUP_VISIBLE_MOVIE.MOVIE_ID IS 'ムービーID';
COMMENT ON COLUMN GROUP_VISIBLE_MOVIE.GROUP_ID IS 'グループID';
COMMENT ON COLUMN GROUP_VISIBLE_MOVIE.VER IS 'バージョン';
COMMENT ON COLUMN GROUP_VISIBLE_MOVIE.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE GROUP_VISIBLE_PHOTO IS 'グループ閲覧可能写真';
COMMENT ON COLUMN GROUP_VISIBLE_PHOTO.GROUP_ID IS 'グループID';
COMMENT ON COLUMN GROUP_VISIBLE_PHOTO.PHOTO_ID IS '写真ID';
COMMENT ON COLUMN GROUP_VISIBLE_PHOTO.VER IS 'バージョン';
COMMENT ON COLUMN GROUP_VISIBLE_PHOTO.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE GRP IS 'グループ';
COMMENT ON COLUMN GRP.GROUP_ID IS 'グループID';
COMMENT ON COLUMN GRP.GROUP_NAME IS 'グループ名';
COMMENT ON COLUMN GRP.VER IS 'バージョン';
COMMENT ON COLUMN GRP.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE INFORMATION IS 'インフォメーション';
COMMENT ON COLUMN INFORMATION.INFO_ID IS 'インフォID';
COMMENT ON COLUMN INFORMATION.TITLE IS 'タイトル';
COMMENT ON COLUMN INFORMATION.INFO_PAGE_PATH IS 'インフォページパス';
COMMENT ON COLUMN INFORMATION.REGISTRATED_DATE IS '登録日時';
COMMENT ON COLUMN INFORMATION.RELEASE_DATE IS '公開日時';
COMMENT ON COLUMN INFORMATION.VER IS 'バージョン';
COMMENT ON COLUMN INFORMATION.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE MENU IS 'メニュー';
COMMENT ON COLUMN MENU.MENU_ID IS 'メニューID';
COMMENT ON COLUMN MENU.MENU_NAME IS 'メニュー名';
COMMENT ON COLUMN MENU.URL IS 'URL';
COMMENT ON COLUMN MENU.HAS_PATHVARIABLES IS 'パス変数を持つ';
COMMENT ON COLUMN MENU.USABLE_START_DATE IS '使用可能開始日時';
COMMENT ON COLUMN MENU.USABLE_END_DATE IS '使用可能終了日時';
COMMENT ON COLUMN MENU.AUTHORITY_LEVEL IS '権限レベル';
COMMENT ON COLUMN MENU.VER IS 'バージョン';
COMMENT ON COLUMN MENU.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE MESSAGE IS 'メッセージ';
COMMENT ON COLUMN MESSAGE.MESSAGE_BOARD_ID IS '掲示板ID';
COMMENT ON COLUMN MESSAGE.MESSAGE_NO IS 'メッセージNo';
COMMENT ON COLUMN MESSAGE.MESSAGE IS 'メッセージ';
COMMENT ON COLUMN MESSAGE.LIKE_COUNT IS 'いいねカウント';
COMMENT ON COLUMN MESSAGE.RELATED_PHOTO_ID IS '関連写真ID';
COMMENT ON COLUMN MESSAGE.RELATED_MOVIE_ID IS '関連ムービーID';
COMMENT ON COLUMN MESSAGE.VER IS 'バージョン';
COMMENT ON COLUMN MESSAGE.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE MESSAGE_BOARD IS '掲示板';
COMMENT ON COLUMN MESSAGE_BOARD.MESSAGE_BOARD_ID IS '掲示板ID';
COMMENT ON COLUMN MESSAGE_BOARD.TITLE IS 'タイトル';
COMMENT ON COLUMN MESSAGE_BOARD.VER IS 'バージョン';
COMMENT ON COLUMN MESSAGE_BOARD.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE MOVIE IS 'ムービー';
COMMENT ON COLUMN MOVIE.MOVIE_ID IS 'ムービーID';
COMMENT ON COLUMN MOVIE.FILE_PATH IS 'ファイルパス';
COMMENT ON COLUMN MOVIE.THUMBNAIL_FILE_PATH IS 'サムネイルファイルパス';
COMMENT ON COLUMN MOVIE.IS_CONTROLED IS '制御有無';
COMMENT ON COLUMN MOVIE.VER IS 'バージョン';
COMMENT ON COLUMN MOVIE.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE MOVIE_RELATED_FOLDER IS 'フォルダ関連ムービー';
COMMENT ON COLUMN MOVIE_RELATED_FOLDER.MOVIE_ID IS 'ムービーID';
COMMENT ON COLUMN MOVIE_RELATED_FOLDER.FOLDER_ID IS 'フォルダID';
COMMENT ON COLUMN MOVIE_RELATED_FOLDER.VER IS 'バージョン';
COMMENT ON COLUMN MOVIE_RELATED_FOLDER.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE MOVIE_RELATED_USER IS 'ユーザ関連ムービー';
COMMENT ON COLUMN MOVIE_RELATED_USER.MOVIE_ID IS 'ムービーID';
COMMENT ON COLUMN MOVIE_RELATED_USER.USER_ID IS 'ユーザID';
COMMENT ON COLUMN MOVIE_RELATED_USER.VER IS 'バージョン';
COMMENT ON COLUMN MOVIE_RELATED_USER.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE NOTIFICATION IS '通知';
COMMENT ON COLUMN NOTIFICATION.INFO_ID IS 'インフォID';
COMMENT ON COLUMN NOTIFICATION.USER_ID IS 'ユーザID';
COMMENT ON COLUMN NOTIFICATION.IS_ACCESSED IS 'アクセス済み';
COMMENT ON COLUMN NOTIFICATION.VER IS 'バージョン';
COMMENT ON COLUMN NOTIFICATION.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE PHOTO IS '写真';
COMMENT ON COLUMN PHOTO.PHOTO_ID IS '写真ID';
COMMENT ON COLUMN PHOTO.FILE_PATH IS 'ファイルパス';
COMMENT ON COLUMN PHOTO.THUMBNAIL_FILE_PATH IS 'サムネイルファイルパス';
COMMENT ON COLUMN PHOTO.IS_CONTROLED IS '制御有無';
COMMENT ON COLUMN PHOTO.VER IS 'バージョン';
COMMENT ON COLUMN PHOTO.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE PHOTO_RELATED_FOLDER IS 'フォルダ関連フォト';
COMMENT ON COLUMN PHOTO_RELATED_FOLDER.PHOTO_ID IS '写真ID';
COMMENT ON COLUMN PHOTO_RELATED_FOLDER.FOLDER_ID IS 'フォルダID';
COMMENT ON COLUMN PHOTO_RELATED_FOLDER.VER IS 'バージョン';
COMMENT ON COLUMN PHOTO_RELATED_FOLDER.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE PHOTO_RELATED_USER IS 'ユーザ関連フォト';
COMMENT ON COLUMN PHOTO_RELATED_USER.PHOTO_ID IS '写真ID';
COMMENT ON COLUMN PHOTO_RELATED_USER.USER_ID IS 'ユーザID';
COMMENT ON COLUMN PHOTO_RELATED_USER.VER IS 'バージョン';
COMMENT ON COLUMN PHOTO_RELATED_USER.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE REQUEST IS '依頼';
COMMENT ON COLUMN REQUEST.REQUEST_ID IS '依頼ID';
COMMENT ON COLUMN REQUEST.TITLE IS 'タイトル';
COMMENT ON COLUMN REQUEST.REQUEST_CONTENTS IS '依頼内容';
COMMENT ON COLUMN REQUEST.REGISTRATED_DATE IS '登録日時';
COMMENT ON COLUMN REQUEST.VER IS 'バージョン';
COMMENT ON COLUMN REQUEST.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE REQUEST_STATUS IS '依頼状況';
COMMENT ON COLUMN REQUEST_STATUS.REQUEST_ID IS '依頼ID';
COMMENT ON COLUMN REQUEST_STATUS.USER_ID IS 'ユーザID';
COMMENT ON COLUMN REQUEST_STATUS.IS_ANSWERED IS '回答済み';
COMMENT ON COLUMN REQUEST_STATUS.IS_APPROVED IS '承認';
COMMENT ON COLUMN REQUEST_STATUS.RESPONSE IS '回答内容';
COMMENT ON COLUMN REQUEST_STATUS.VER IS 'バージョン';
COMMENT ON COLUMN REQUEST_STATUS.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE USER_RELATED_FOLDER IS 'ユーザ関連フォルダ';
COMMENT ON COLUMN USER_RELATED_FOLDER.FOLDER_ID IS 'フォルダID';
COMMENT ON COLUMN USER_RELATED_FOLDER.USER_ID IS 'ユーザID';
COMMENT ON COLUMN USER_RELATED_FOLDER.VER IS 'バージョン';
COMMENT ON COLUMN USER_RELATED_FOLDER.LAST_UPDATED_DATE IS '最終更新日時';
COMMENT ON TABLE USR IS 'ユーザ';
COMMENT ON COLUMN USR.USER_ID IS 'ユーザID';
COMMENT ON COLUMN USR.LAST_NAME IS '苗字';
COMMENT ON COLUMN USR.FIRST_NAME IS '名前';
COMMENT ON COLUMN USR.LOGIN_ID IS 'ログインID';
COMMENT ON COLUMN USR.IMAGE_FILE_PATH IS '画像ファイルパス';
COMMENT ON COLUMN USR.AUTHORITY_LEVEL IS '権限レベル';
COMMENT ON COLUMN USR.IS_BRIDE_SIDE IS '花嫁側';
COMMENT ON COLUMN USR.LAST_LOGIN_DATE IS '最終ログイン日時';
COMMENT ON COLUMN USR.VER IS 'バージョン';
COMMENT ON COLUMN USR.LAST_UPDATED_DATE IS '最終更新日時';



