spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wedding
    username: wedding_app
    password: wedding_app
    driverClassName: org.postgresql.Driver
operation:
  backup:
    root:
      directory: /Users/kawabatakouhei/Documents/work/apps