
/* Drop Tables */

DROP TABLE IF EXISTS CREDENTIAL;
DROP TABLE IF EXISTS MENU;
DROP TABLE IF EXISTS USR;




/* Create Tables */

CREATE TABLE CREDENTIAL
(
	USER_ID varchar(8) NOT NULL,
	CREDENTIAL_TYPE varchar NOT NULL,
	CREDENTIAL_KEY varchar,
	VALID_DATE date,
	PRIMARY KEY (CREDENTIAL_TYPE),
	UNIQUE (USER_ID, CREDENTIAL_TYPE)
) WITHOUT OIDS;


CREATE TABLE MENU
(
	MENU_ID varchar(4) NOT NULL,
	MENU_NAME varchar,
	FUNCTION_ID varchar(4),
	USABLE_START_DATE date,
	USABLE_END_DATE date,
	PRIMARY KEY (MENU_ID)
) WITHOUT OIDS;


CREATE TABLE USR
(
	USER_ID varchar(8) NOT NULL,
	USER_NAME varchar,
	LOGIN_ID varchar UNIQUE,
	LAST_LOGIN_DATE date,
	PRIMARY KEY (USER_ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE CREDENTIAL
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USR (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



